version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop-performance
    versions:
    - 1.8.1
  - dependency-name: rubocop-rspec
    versions:
    - 1.44.1
